<?php

namespace App\Modules\HR\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class HRRequest extends FormRequest
{
    public function rules(): array
    {
        return match ($this->route()?->getName()) {
            'hr.departments.store','hr.departments.update' => ['parent_id' => ['nullable', 'integer', 'exists:hr_departments,id'], 'manager_employee_id' => ['nullable', 'integer', 'exists:hr_employees,id'], 'code' => ['required', 'string', 'max:50'], 'name' => ['required', 'string', 'max:255'], 'description' => ['nullable', 'string']],
            'hr.teams.store','hr.teams.update' => ['department_id' => ['required', 'integer', 'exists:hr_departments,id'], 'manager_employee_id' => ['nullable', 'integer', 'exists:hr_employees,id'], 'code' => ['required', 'string', 'max:50'], 'name' => ['required', 'string', 'max:255']],
            'hr.positions.store','hr.positions.update' => ['department_id' => ['nullable', 'integer', 'exists:hr_departments,id'], 'code' => ['required', 'string', 'max:50'], 'title' => ['required', 'string', 'max:255'], 'description' => ['nullable', 'string'], 'min_salary' => ['nullable', 'numeric', 'min:0'], 'max_salary' => ['nullable', 'numeric', 'gte:min_salary'], 'is_active' => ['required', 'boolean']],
            'hr.employees.store','hr.employees.update' => ['user_id' => ['nullable', 'integer', 'exists:users,id'], 'department_id' => ['nullable', 'integer', 'exists:hr_departments,id'], 'team_id' => ['nullable', 'integer', 'exists:hr_teams,id'], 'manager_id' => ['nullable', 'integer', 'exists:hr_employees,id'], 'employee_number' => ['required', 'string', 'max:50'], 'name' => ['required', 'string', 'max:255'], 'email' => ['nullable', 'email'], 'phone' => ['nullable', 'string'], 'address' => ['nullable', 'array'], 'position' => ['nullable', 'string'], 'employment_type' => ['nullable', Rule::in(['full_time', 'part_time', 'contractor', 'intern', 'temporary'])], 'work_location' => ['nullable', 'string', 'max:255'], 'hire_date' => ['required', 'date'], 'probation_ends_on' => ['nullable', 'date', 'after_or_equal:hire_date'], 'termination_date' => ['nullable', 'date', 'after_or_equal:hire_date'], 'resignation_date' => ['nullable', 'date', 'after_or_equal:hire_date'], 'status' => ['required', Rule::in(['active', 'inactive', 'on_leave', 'terminated', 'resigned'])], 'base_salary' => ['required', 'numeric', 'min:0'], 'currency' => ['required', 'string', 'size:3'], 'payroll_formula' => ['nullable', 'array']],
            'hr.self.update' => ['phone' => ['nullable', 'string'], 'address' => ['nullable', 'array'], 'personal_detail' => ['nullable', 'array'], 'personal_detail.date_of_birth' => ['nullable', 'date'], 'personal_detail.gender' => ['nullable', 'string', 'max:50'], 'personal_detail.nationality' => ['nullable', 'string', 'max:100'], 'personal_detail.marital_status' => ['nullable', 'string', 'max:50'], 'personal_detail.address' => ['nullable', 'array']],
            'hr.personal-details.store','hr.personal-details.update' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'date_of_birth' => ['nullable', 'date'], 'gender' => ['nullable', 'string', 'max:50'], 'nationality' => ['nullable', 'string', 'max:100'], 'national_id' => ['nullable', 'string', 'max:100'], 'marital_status' => ['nullable', 'string', 'max:50'], 'address' => ['nullable', 'array']],
            'hr.emergency-contacts.store','hr.emergency-contacts.update' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'name' => ['required', 'string', 'max:255'], 'relationship' => ['nullable', 'string', 'max:100'], 'phone' => ['required', 'string', 'max:100'], 'email' => ['nullable', 'email'], 'is_primary' => ['required', 'boolean']],
            'hr.contracts.store','hr.contracts.update' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'contract_number' => ['required', 'string', 'max:100'], 'type' => ['required', 'string', 'max:100'], 'starts_on' => ['required', 'date'], 'ends_on' => ['nullable', 'date', 'after_or_equal:starts_on'], 'salary' => ['required', 'numeric', 'min:0'], 'currency' => ['required', 'string', 'size:3'], 'status' => ['required', Rule::in(['draft', 'active', 'expired', 'terminated'])], 'terms' => ['nullable', 'array']],
            'hr.holidays.store','hr.holidays.update' => ['name' => ['required', 'string', 'max:255'], 'holiday_date' => ['required', 'date'], 'is_paid' => ['required', 'boolean'], 'region' => ['nullable', 'string', 'max:100']],
            'hr.leave-types.store','hr.leave-types.update' => ['name' => ['required', 'string'], 'code' => ['required', 'string', 'max:50'], 'annual_allowance' => ['required', 'numeric', 'min:0'], 'is_paid' => ['required', 'boolean'], 'requires_approval' => ['required', 'boolean']],
            'hr.leave-balances.adjust' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'leave_type_id' => ['required', 'integer', 'exists:hr_leave_types,id'], 'year' => ['required', 'integer', 'min:2000', 'max:2100'], 'days' => ['required', 'numeric'], 'reason' => ['nullable', 'string']],
            'hr.leave.store' => ['leave_type_id' => ['required', 'integer', 'exists:hr_leave_types,id'], 'starts_on' => ['required', 'date'], 'ends_on' => ['required', 'date', 'after_or_equal:starts_on'], 'reason' => ['nullable', 'string']],
            'hr.leave.review' => ['status' => ['required', Rule::in(['approved', 'rejected'])], 'review_notes' => ['nullable', 'string']],
            'hr.attendance.store' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'work_date' => ['required', 'date'], 'clock_in' => ['nullable', 'date'], 'clock_out' => ['nullable', 'date', 'after:clock_in'], 'hours' => ['nullable', 'numeric', 'min:0', 'max:24'], 'source' => ['nullable', 'string', 'max:50'], 'notes' => ['nullable', 'string']],
            'hr.benefits.store','hr.benefits.update' => ['name' => ['required', 'string', 'max:255'], 'type' => ['required', 'string', 'max:100'], 'default_amount' => ['required', 'numeric', 'min:0'], 'taxable' => ['required', 'boolean'], 'is_active' => ['required', 'boolean']],
            'hr.employee-benefits.store','hr.employee-benefits.update' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'benefit_id' => ['required', 'integer', 'exists:hr_benefits,id'], 'amount' => ['required', 'numeric', 'min:0'], 'starts_on' => ['nullable', 'date'], 'ends_on' => ['nullable', 'date', 'after_or_equal:starts_on'], 'status' => ['required', Rule::in(['active', 'inactive', 'expired'])]],
            'hr.payroll-runs.store' => ['name' => ['required', 'string'], 'period_start' => ['required', 'date'], 'period_end' => ['required', 'date', 'after_or_equal:period_start'], 'pay_date' => ['required', 'date'], 'status' => ['nullable', Rule::in(['draft'])]],
            'hr.payroll-runs.process' => ['items' => ['nullable', 'array'], 'items.*.employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'items.*.bonuses' => ['nullable', 'numeric', 'min:0'], 'items.*.deductions' => ['nullable', 'numeric', 'min:0'], 'items.*.tax_rate' => ['nullable', 'numeric', 'min:0', 'max:100']],
            'hr.onboarding.store','hr.onboarding.update','hr.offboarding.store','hr.offboarding.update' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'title' => ['required', 'string', 'max:255'], 'description' => ['nullable', 'string'], 'assigned_to' => ['nullable', 'integer', 'exists:users,id'], 'due_on' => ['nullable', 'date'], 'status' => ['required', Rule::in(['pending', 'in_progress', 'completed', 'cancelled'])], 'completed_at' => ['nullable', 'date']],
            'hr.performance.store','hr.performance.update' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'reviewer_id' => ['nullable', 'integer', 'exists:users,id'], 'period' => ['required', 'string', 'max:100'], 'score' => ['nullable', 'numeric', 'min:0', 'max:100'], 'status' => ['required', Rule::in(['draft', 'in_review', 'completed'])], 'goals' => ['nullable', 'array'], 'summary' => ['nullable', 'string'], 'reviewed_on' => ['nullable', 'date']],
            'hr.disciplinary.store','hr.disciplinary.update' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'issued_by' => ['nullable', 'integer', 'exists:users,id'], 'type' => ['required', 'string', 'max:100'], 'reason' => ['required', 'string'], 'issued_on' => ['required', 'date'], 'status' => ['required', Rule::in(['open', 'resolved', 'withdrawn'])], 'resolution' => ['nullable', 'string']],
            'hr.training.store','hr.training.update' => ['employee_id' => ['required', 'integer', 'exists:hr_employees,id'], 'title' => ['required', 'string', 'max:255'], 'provider' => ['nullable', 'string', 'max:255'], 'started_on' => ['nullable', 'date'], 'completed_on' => ['nullable', 'date', 'after_or_equal:started_on'], 'status' => ['required', Rule::in(['planned', 'in_progress', 'completed', 'cancelled'])], 'cost' => ['nullable', 'numeric', 'min:0'], 'currency' => ['nullable', 'string', 'size:3']],
            'hr.documents.store' => ['type' => ['required', 'string', 'max:100'], 'name' => ['required', 'string'], 'file' => ['required', 'file', 'max:20480'], 'notes' => ['nullable', 'string']],
            'hr.jobs.store','hr.jobs.update' => ['department_id' => ['nullable', 'integer', 'exists:hr_departments,id'], 'title' => ['required', 'string'], 'description' => ['nullable', 'string'], 'status' => ['required', Rule::in(['draft', 'open', 'closed'])], 'closes_on' => ['nullable', 'date']],
            'hr.applicants.store' => ['name' => ['required', 'string'], 'email' => ['required', 'email'], 'phone' => ['nullable', 'string'], 'stage' => ['nullable', Rule::in(['applied', 'screening', 'interview', 'offer', 'hired', 'rejected'])], 'notes' => ['nullable', 'string'], 'resume' => ['nullable', 'file', 'max:20480']],
            'hr.applicants.update' => ['stage' => ['required', Rule::in(['applied', 'screening', 'interview', 'offer', 'hired', 'rejected'])], 'notes' => ['nullable', 'string']],
            default => []
        };
    }
}
