<?php

use App\Modules\HR\Http\Controllers\HRController;
use App\Modules\HR\Http\Controllers\HRReportController;
use App\Modules\HR\Http\Controllers\LeaveController;
use App\Modules\HR\Http\Controllers\PayrollController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth:sanctum')->prefix('hr')->name('hr.')->group(function () {
    Route::get('departments', [HRController::class, 'departments'])->name('departments.index');
    Route::post('departments', [HRController::class, 'storeDepartment'])->name('departments.store');
    Route::put('departments/{department}', [HRController::class, 'updateDepartment'])->name('departments.update');
    Route::get('teams', [HRController::class, 'teams'])->name('teams.index');
    Route::post('teams', [HRController::class, 'storeTeam'])->name('teams.store');
    Route::put('teams/{team}', [HRController::class, 'updateTeam'])->name('teams.update');
    Route::get('positions', [HRController::class, 'positions'])->name('positions.index');
    Route::post('positions', [HRController::class, 'storePosition'])->name('positions.store');
    Route::put('positions/{position}', [HRController::class, 'updatePosition'])->name('positions.update');
    Route::get('employees', [HRController::class, 'employees'])->name('employees.index');
    Route::post('employees', [HRController::class, 'storeEmployee'])->name('employees.store');
    Route::get('employees/{employee}', [HRController::class, 'showEmployee'])->name('employees.show');
    Route::put('employees/{employee}', [HRController::class, 'updateEmployee'])->name('employees.update');
    Route::post('employees/{employee}/documents', [HRController::class, 'document'])->name('documents.store');
    Route::get('documents/versions/{version}/download', [HRController::class, 'downloadDocument'])->name('documents.download');
    Route::get('personal-details', [HRController::class, 'personalDetails'])->name('personal-details.index');
    Route::post('personal-details', [HRController::class, 'savePersonalDetail'])->name('personal-details.store');
    Route::put('personal-details/{personalDetail}', [HRController::class, 'savePersonalDetail'])->name('personal-details.update');
    Route::get('emergency-contacts', [HRController::class, 'emergencyContacts'])->name('emergency-contacts.index');
    Route::post('emergency-contacts', [HRController::class, 'saveEmergencyContact'])->name('emergency-contacts.store');
    Route::put('emergency-contacts/{contact}', [HRController::class, 'saveEmergencyContact'])->name('emergency-contacts.update');
    Route::get('contracts', [HRController::class, 'contracts'])->name('contracts.index');
    Route::post('contracts', [HRController::class, 'saveContract'])->name('contracts.store');
    Route::put('contracts/{contract}', [HRController::class, 'saveContract'])->name('contracts.update');
    Route::get('holidays', [HRController::class, 'holidays'])->name('holidays.index');
    Route::post('holidays', [HRController::class, 'saveHoliday'])->name('holidays.store');
    Route::put('holidays/{holiday}', [HRController::class, 'saveHoliday'])->name('holidays.update');
    Route::get('leave-types', [HRController::class, 'leaveTypes'])->name('leave-types.index');
    Route::post('leave-types', [HRController::class, 'storeLeaveType'])->name('leave-types.store');
    Route::put('leave-types/{leaveType}', [HRController::class, 'updateLeaveType'])->name('leave-types.update');
    Route::get('leave-balances', [HRController::class, 'leaveBalances'])->name('leave-balances.index');
    Route::post('leave-balances/adjustments', [HRController::class, 'adjustLeaveBalance'])->name('leave-balances.adjust');
    Route::get('leave-requests', [LeaveController::class, 'index'])->name('leave.index');
    Route::post('leave-requests', [LeaveController::class, 'store'])->name('leave.store');
    Route::post('leave-requests/{leaveRequest}/review', [LeaveController::class, 'review'])->name('leave.review');
    Route::get('attendance', [HRController::class, 'attendance'])->name('attendance.index');
    Route::post('attendance', [HRController::class, 'storeAttendance'])->name('attendance.store');
    Route::get('benefits', [HRController::class, 'benefits'])->name('benefits.index');
    Route::post('benefits', [HRController::class, 'saveBenefit'])->name('benefits.store');
    Route::put('benefits/{benefit}', [HRController::class, 'saveBenefit'])->name('benefits.update');
    Route::get('employee-benefits', [HRController::class, 'employeeBenefits'])->name('employee-benefits.index');
    Route::post('employee-benefits', [HRController::class, 'saveEmployeeBenefit'])->name('employee-benefits.store');
    Route::put('employee-benefits/{employeeBenefit}', [HRController::class, 'saveEmployeeBenefit'])->name('employee-benefits.update');
    Route::get('payroll-runs', [PayrollController::class, 'index'])->name('payroll-runs.index');
    Route::post('payroll-runs', [PayrollController::class, 'store'])->name('payroll-runs.store');
    Route::post('payroll-runs/{run}/process', [PayrollController::class, 'process'])->name('payroll-runs.process');
    Route::get('payslips/{item}/pdf', [PayrollController::class, 'payslip'])->name('payslips.pdf');
    Route::post('payslips/{item}/email', [PayrollController::class, 'email'])->name('payslips.email');
    Route::get('onboarding-tasks', [HRController::class, 'onboarding'])->name('onboarding.index');
    Route::post('onboarding-tasks', [HRController::class, 'saveOnboarding'])->name('onboarding.store');
    Route::put('onboarding-tasks/{task}', [HRController::class, 'saveOnboarding'])->name('onboarding.update');
    Route::get('offboarding-tasks', [HRController::class, 'offboarding'])->name('offboarding.index');
    Route::post('offboarding-tasks', [HRController::class, 'saveOffboarding'])->name('offboarding.store');
    Route::put('offboarding-tasks/{task}', [HRController::class, 'saveOffboarding'])->name('offboarding.update');
    Route::get('performance-reviews', [HRController::class, 'performanceReviews'])->name('performance.index');
    Route::post('performance-reviews', [HRController::class, 'savePerformanceReview'])->name('performance.store');
    Route::put('performance-reviews/{review}', [HRController::class, 'savePerformanceReview'])->name('performance.update');
    Route::get('disciplinary-actions', [HRController::class, 'disciplinaryActions'])->name('disciplinary.index');
    Route::post('disciplinary-actions', [HRController::class, 'saveDisciplinaryAction'])->name('disciplinary.store');
    Route::put('disciplinary-actions/{action}', [HRController::class, 'saveDisciplinaryAction'])->name('disciplinary.update');
    Route::get('training-records', [HRController::class, 'trainingRecords'])->name('training.index');
    Route::post('training-records', [HRController::class, 'saveTrainingRecord'])->name('training.store');
    Route::put('training-records/{record}', [HRController::class, 'saveTrainingRecord'])->name('training.update');
    Route::get('jobs', [HRController::class, 'jobs'])->name('jobs.index');
    Route::post('jobs', [HRController::class, 'storeJob'])->name('jobs.store');
    Route::put('jobs/{job}', [HRController::class, 'updateJob'])->name('jobs.update');
    Route::post('jobs/{job}/applicants', [HRController::class, 'applicant'])->name('applicants.store');
    Route::put('applicants/{applicant}', [HRController::class, 'updateApplicant'])->name('applicants.update');
    Route::get('applicants/{applicant}/resume', [HRController::class, 'downloadResume'])->name('applicants.resume');
    Route::get('me', [HRController::class, 'me'])->name('self.show');
    Route::put('me', [HRController::class, 'updateMe'])->name('self.update');
    Route::get('me/leave-balances', [HRController::class, 'meLeaveBalances'])->name('self.leave-balances');
    Route::get('me/attendance-summary', [HRController::class, 'meAttendanceSummary'])->name('self.attendance-summary');
    Route::get('me/training', [HRController::class, 'meTraining'])->name('self.training');
    Route::get('me/performance', [HRController::class, 'mePerformance'])->name('self.performance');
    Route::get('me/leave-requests', [LeaveController::class, 'mine'])->name('self.leave');
    Route::get('me/payslips', [PayrollController::class, 'mine'])->name('self.payslips');
    Route::get('reports/{report}', [HRReportController::class, 'show'])->name('reports.show');
});
